version: 1.0.{build}
image:
- Visual Studio 2019 Preview
- Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: SIS.sln
  parallel: true
  verbosity: minimal